############################### Navigation Bar ############################### > start
navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title:
  menu:
    - name: 博客
      icon: fas fa-rss
      url: /
    - name: 留言板
      icon: fa fa-sticky-note
      url: message_board/
    - name: 友人帐
      icon: fas fa-link
      url: https://blog.moej.cn/links.html
      rel: nofollow
    - name: 关于我
      icon: fas fa-info-circle
      url: about/
      rel: nofollow
    - name: 捉迷藏
      icon: fas fa-ellipsis-v
      rows:
        - name: 音乐
          icon: fas fa-compact-disc    
        - name: hr
        - name: 分类
          icon: fas fa-folder-open
          url: categories/  
        - name: 标签
          icon: fas fa-tags
          url: tags/ 
        - name: 文章归档
          icon: fas fa-archive
          url: archives/       
        - name: hr
        - name: 学习&生活
        - name: 收藏音乐
          icon: fas fa-compact-disc
          url: /favorite_things/
        - name: 笔记本
          icon: fas fa-book
          url: https://docs.cwxyr.me/
        - name: 计划表
          icon: fas fa-list
          url: /schedule/
    - name: 生活站
      icon: fa fa-tree
      url: https://blog.moej.cn/
    - name: Travelling
      icon: fa fa-plane
      url: https://travellings.now.sh/

  search: 搜索...   # Search bar placeholder
############################### Navigation Bar ############################### > end

pages:
  # 友链页面配置
  friends:
    layout_scheme: sites # simple: 简单布局, traditional: 传统布局,  sites: 网站卡片布局

article:
  body:
    # meta library
    meta_library:
      # 默认文章作者（可在 front-matter 中覆盖）
      author:
        avatar: https://cdn2.sublimerui.top/2020/10/11/b0f0cc056bb52.png
        name: 果子酱
        url: https://cwxyr.me
      # 文章创建日期          

############################### Cover ############################### > start
cover:
  height_scheme: full # full, half
  layout_scheme: dock # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  background: https://cdn2.sublimerui.top/2020/10/11/00ed4f7376d3b.png # https://cdn.jsdelivr.net/gh/cwxyr/mycdn@master/wallhaven-lmo76p.jpg # https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/033.jpg
  logo: https://cdn.jsdelivr.net/gh/cwxyr/mycdn@master/logo_new.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-Cover@3x.png
  title: ''
  subtitle: ''
  search: 一搜啥都有... # search bar placeholder
  features:
    - name: 引导页
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f5c3.svg
      url: https://cwxyr.me
    #- name: 帮助
    #  icon: #
    #  img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f516.svg
    #  url: faqs/
    #- name: 示例
    #  icon: #
    #  img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f396.svg
    #  url: /examples/
    - name: 留言板
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f389.svg
      url: https://blog.moej.cn/inbox.html
    - name: 生活站
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: https://blog.moej.cn/
    - name: 图床
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f9ec.svg
      url: https://picture.moefan.icu/
############################### Cover ############################### > end

############################### Sidebar ############################### > start
sidebar:
  # 主页、分类、归档等独立页面
  for_page: [blogger, mylist, category, tagcloud, webinfo, visitors_global]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    # ---------------------------------------
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://cdn2.sublimerui.top/2020/10/11/b0f0cc056bb52.png
      shape: rectangle # circle, rectangle
      url: /about/
      title:
      subtitle:
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
        - icon: fas fa-rss
          url: /atom.xml
        - icon: fas fa-envelope
          url: mailto:466491019@qq.com
        - icon: fab fa-github
          url: https://github.com/cwxyr/
        - icon: fas fa-headphones-alt
          url: https://music.163.com/#/user/home?id=299199250
    # ---------------------------------------
    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-list
        title: 本文目录
      list_number: false
      min_depth: 2
      max_depth: 5
    # ---------------------------------------
    # category widget
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: 文章分类
        url: /blog/categories/
    # ---------------------------------------
    # tagcloud widget
    tagcloud:
      class: tagcloud
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-tags
        title: 热门标签
        url: /blog/tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: '#999'
      end_color: '#555'

    # ---------------------------------------
    # qrcode widget
    donate:
      class: qrcode
      display: [desktop, mobile] # [desktop, mobile]
      height: 64px  # Automatic height if not set
      images:
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
    # ---------------------------------------
    # webinfo widget
    webinfo:
      class: webinfo
      display: [desktop]
      header:
        icon: fas fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2020/01/01'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: true
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          service: leancloud  # busuanzi, leancloud
          siteuv:
            enable: true
            text: '本站访客数：'
            unit: '人'
          sitepv:
            enable: true
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'
    visitors_global:
      class: text
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-award
        title: 访客地球
        # url: https://github.com/xaoxuu/
      content:
        # - '<center><img src="https://i.loli.net/2020/02/11/s1ayTzAfJF5DQMt.png"></center>'
        - '<script type="text/javascript" src="//rf.revolvermaps.com/0/0/8.js?i=5vaufw69zyz&m=7&c=ff0000&cr1=ffffff&f=times_new_roman&l=33" async="async"></script>'

    notice:
      class: text
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-star
        title: 文章更新较慢(Ｔ▽Ｔ)
        # url: https://github.com/xaoxuu/
      content:
        # - '<center><img src="https://i.loli.net/2020/02/11/s1ayTzAfJF5DQMt.png"></center>'
        - '<center>博主备战21考研(Ｔ▽Ｔ)</center>'
        - '<center>欢迎留言，不定时回复=_=</center>'
        - '<center>祝各位考研狗们都成功上岸喔~</center>'
    mylist:
      class: list
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-star
        title: 博主的小天地
      rows:
        - name: 生活站-Sakura
          url: https://blog.moej.cn
        - name: Moe-Fan图床
          url: https://picture.moefan.icu/

############################### Sidebar ############################### > end

comments:
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  service: valine # valine, minivaline, disqus, gitalk, vssue, livere, isso, hashover
  # Valine
  # https://valine.js.org/
  valine:
    appId: NUIvWmBVy0NYRGpzYbzFaK5b-gzGzoHsz # your appId
    appKey: hpOy65rB00YTyHxaVmx93woY # your appKey
    # js: https://cdn.jsdelivr.net/npm/valine@1.4/dist/Valine.min.js
    path: # 全局评论地址
    placeholder: 快来评论吧~  # 评论占位提示
    meta: nick,mail,link # valine comment header info
    requiredFields: ['nick','mail']
    enableQQ: true # Unstable avatar link
    recordIP: false # Record commenter IP
    avatar: robohash # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    lang: zh-cn
    highlight: true
    visitor: true
    mathJax: false



site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [motto, social, license, info, copyright, travellings]
  social:
    - icon: fas fa-rss
      url: atom.xml
    - icon: fas fa-envelope
      url: mailto:466491019@qq.com
    - icon: fab fa-github
      url: https://github.com/cwxyr
    - icon: fas fa-headphones-alt
      url: https://music.163.com/#/user/home?id=299199250
  copyright: '[Copyright © 2017-2020 Sublime.&&果子酱](https://sublimerui.top)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'
  motto: '**你一定要努力，才能和更好的人相遇**'
  travellings: '<a href="https://travellings.now.sh/" target="_blank" title="开往-友链接力" rel="external nofollow noopener noreferrer"><img src="https://cdn.jsdelivr.net/gh/cwxyr/mycdn@master/travellings_1.png" alt="开往-友链接力" width="100"></a>'    

################################################################################################

plugins:
################ required plugins ################
  # jquery
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.5/dist/jquery.min.js
  # fontawesome
  fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14/css/all.min.css

  ################ optional plugins ################

  ######## Plugins to improve loading speed:

  # 预加载
  preload:
    enable: true
    service: flying_pages # instant_page, flying_pages
    instant_page: https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@2/js/instant_page.js
    flying_pages: https://cdn.jsdelivr.net/gh/gijo-varghese/flying-pages@2.1.2/flying-pages.min.js

  # 图片懒加载
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true
    js: https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.1.0/dist/lazyload.min.js
    onlypost: false
    loadingImg: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/placeholder/c617bfd2497fcea598e621413e315c368f8d8e.svg
    blurIn: true # 模糊加载效果 （loadingImg为空时有效）

  ######## Plugins to optimize the experience:

  # highlight.js
  highlightjs:
    enable: true # Please set hexo.config.highlight.enable = false !!!
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@9.18.1/styles/solarized-light.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    enable: #true
    js: https://cdn.jsdelivr.net/npm/scrollreveal@4.0.6/dist/scrollreveal.min.js
    distance: 32px
    duration: 800 # ms
    interval: 20 # ms
    scale: 1 # 0.1~1

  # Codeblock Copy Button
  clipboard:
    enable: true
    js: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js

  ######## Plugins for SEO:

  # npm i hexo-wordcount
  wordcount:
    enable: true

  ######## Plugins for ...
  # Button Ripple Effect
  nodewaves:
    enable: #true
    css: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.css
    js: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.js

  # fontawesome animation
  fontawesome_animation:
    enable: #true
    css: https://cdn.jsdelivr.net/gh/l-lin/font-awesome-animation/dist/font-awesome-animation.min.css

  # Typing Effects
  comment_typing:
    enable: true
    js: https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@2/js/comment_typing.js

  # Slide Background
  backstretch:
    enable: true
    js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
    position: fixed       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 15000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      - https://cdn2.sublimerui.top/2020/10/11/00ed4f7376d3b.png
      - https://cdn2.sublimerui.top/2020/09/25/4fd80788ed093.png
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/001.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/002.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/003.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/004.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/005.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/006.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/012.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/016.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/019.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/025.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/033.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/034.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/035.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/038.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/039.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/042.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/046.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/051.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/052.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/054.jpg
      #- https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/056.jpg

  # APlayer is only available in mainland China.
  # APlayer config: https://github.com/metowolf/MetingJS
  aplayer:
    enable: #true
    js:
      - https://cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js
      - https://cdn.jsdelivr.net/npm/meting@2.0/dist/Meting.min.js
    # Required
    server: netease   # netease, tencent, kugou, xiami, baidu
    type: playlist    # song, playlist, album, search, artist
    id: 3175833810    # song id / playlist id / album id / search keyword
    # Optional
    fixed: false      # enable fixed mode
    theme: '#1BCDFC'  # main color
    autoplay: false   # audio autoplay
    order: list       # player play order, values: 'list', 'random'
    loop: all         # player loop play, values: 'all', 'one', 'none'
    volume: 0.7       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    list_max_height: 320px # list max height
    list_folded: true
  pjax:
    enable: true
    timeout: 5000        # The timeout in milliseconds for the XHR requests. Set to 0 to disable the timeout.
    cacheBust: false     # When set to true, Pjax appends a timestamp  to skip the browser cache.
    animation: nprogress # nprogress, circle
    banUrl:              # 被屏蔽的 url 地址将不启用 pjax 跳转，可以在控制台下使用 window.location.pathname 获取
      # - /artitalk/     # artitalk 不支持 pjax


  # Artitalk https://artitalk.js.org
  # 配置过程请参考：https://artitalk.js.org/doc.html
  # 除appID和appKEY外均为选填项
  artitalk:
    # Set `layout: artitalk` to enable in page
    appID: ogP8qj3veMh0LFpFWMPOyF0X-MdYXbMMI # your appID
    appKEY: nHXLd3N3Jgh460t2iRQKWAtr # your appKEY
    # severurl:  #leancloud绑定的安全域名，使用国际版的话不需要填写
    # slanguage: # 语言设置，zh为汉语，en为英语，es为西班牙语。默认为汉语
    # per: #每页说说的显示数量
    # placeholder1: #在编辑说说的输入框中的占位符
    # placeholder2: #自定义头像url的输入框的占位符
    # lazy: #加载动画的开关，1为开，0为关，默认为开
    # bgimg: #说说输入框背景图片url
    # color1: #说说背景颜色1&按钮颜色1
    # color2: #说说背景颜色2&按钮颜色2
    # color3: #说说字体颜色
  ##################################
  # 暗黑模式 darkmodejs
  # https://darkmodejs.learn.uno
  # 暗黑模式样式：https://github.com/volantis-x/hexo-theme-volantis/blob/master/source/css/_third-party/darkmode.styl
  darkmodejs:
    enable:
    js: https://cdn.jsdelivr.net/npm/darkmode-js@1.5/lib/darkmode-js.min.js
    button: # button 使用默认或自行开发
      enable: true
      left: '16px'
      bottom: '32px'
      buttonDark: '#333'
      buttonLight: '#ddd'
    compatible: true # 卡片兼容性处理，如果未发现卡片出现兼容问题设置为false
