############################### Navigation Bar ############################### > start
navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title:
  menu:
    - name: 博客
      icon: fas fa-rss
      url: /
    - name: 分类
      icon: fas fa-folder-open
      url: categories/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 归档
      icon: fas fa-archive
      url: archives/
    - name: 友人帐
      icon: fas fa-link
      url: friends/
    - name: 关于我
      icon: fas fa-info-circle
      url: about/
    - name: Travelling
      icon: fa fa-plane
      url: https://travellings.now.sh/        
  search: 搜索...   # Search bar placeholder
############################### Navigation Bar ############################### > end

pages:
  # 友链页面配置
  friends:
    layout_scheme: sites # simple: 简单布局, traditional: 传统布局,  sites: 网站卡片布局

article:
  body:
    # meta library
    meta_library:
      # 默认文章作者（可在 front-matter 中覆盖）
      author:
        avatar: https://cdn2.sublimerui.top/2020/10/11/b0f0cc056bb52.png
        name: 果子酱
        url: https://cwxyr.me
      # 文章创建日期          

############################### Cover ############################### > start
cover:
  height_scheme: full # full, half
  layout_scheme: dock # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  background: https://cdn2.sublimerui.top/2020/10/11/00ed4f7376d3b.png # https://cdn.jsdelivr.net/gh/cwxyr/mycdn@master/wallhaven-lmo76p.jpg # https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/033.jpg
  logo: https://cdn.jsdelivr.net/gh/cwxyr/mycdn@master/logo_new.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-Cover@3x.png
  title: ''
  subtitle: ''
  search: 一搜啥都有... # search bar placeholder
  features:
    - name: 文档
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f5c3.svg
      url: /v4/getting-started/
    - name: 帮助
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f516.svg
      url: faqs/
    - name: 示例
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f396.svg
      url: /examples/
    - name: 社区
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f389.svg
      url: /contributors/
    - name: 博客
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: /archives/
    - name: 源码
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f9ec.svg
      url: https://github.com/volantis-x/hexo-theme-volantis/
############################### Cover ############################### > end

############################### Sidebar ############################### > start
sidebar:
  # 主页、分类、归档等独立页面
  for_page: [blogger, notice, mylist, category, tagcloud, webinfo]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    # ---------------------------------------
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://cdn2.sublimerui.top/2020/10/11/b0f0cc056bb52.png
      shape: rectangle # circle, rectangle
      url: /about/
      title:
      subtitle:
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
        - icon: fas fa-rss
          url: /atom.xml
        - icon: fas fa-envelope
          url: mailto:me@xxx.com
        - icon: fab fa-github
          url: https://github.com/volantis-x/
        - icon: fas fa-headphones-alt
          url: /
    # ---------------------------------------
    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-list
        title: 本文目录
      list_number: false
      min_depth: 2
      max_depth: 5
    # ---------------------------------------
    # category widget
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: 文章分类
        url: /blog/categories/
    # ---------------------------------------
    # tagcloud widget
    tagcloud:
      class: tagcloud
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-tags
        title: 热门标签
        url: /blog/tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: '#999'
      end_color: '#555'

    # ---------------------------------------
    # qrcode widget
    donate:
      class: qrcode
      display: [desktop, mobile] # [desktop, mobile]
      height: 64px  # Automatic height if not set
      images:
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
    # ---------------------------------------
    # webinfo widget
    webinfo:
      class: webinfo
      display: [desktop]
      header:
        icon: fas fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2020/01/01'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: true
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          service: leancloud  # busuanzi, leancloud
          siteuv:
            enable: true
            text: '本站访客数：'
            unit: '人'
          sitepv:
            enable: true
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'

    notice:
      class: text
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-star
        title: 文章更新较慢(Ｔ▽Ｔ)
        # url: https://github.com/xaoxuu/
      content:
        # - '<center><img src="https://i.loli.net/2020/02/11/s1ayTzAfJF5DQMt.png"></center>'
        - '<center>博主备战21考研(Ｔ▽Ｔ)</center>'
        - '<center>欢迎留言，不定时回复=_=</center>'
        - '<center>祝各位考研狗们都成功上岸喔~</center>'
    mylist:
      class: list
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-star
        title: 博主的小天地
      rows:
        - name: 生活站-Sakura
          url: https://blog.cwxyr.me
        - name: Moe-Fan图床
          url: https://picture.moefan.icu/

############################### Sidebar ############################### > end

comments:
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  service: valine # valine, minivaline, disqus, gitalk, vssue, livere, isso, hashover
  # Valine
  # https://valine.js.org/
  valine:
    appId: NUIvWmBVy0NYRGpzYbzFaK5b-gzGzoHsz # your appId
    appKey: hpOy65rB00YTyHxaVmx93woY # your appKey
    # js: https://cdn.jsdelivr.net/npm/valine@1.4/dist/Valine.min.js
    path: # 全局评论地址
    placeholder: 快来评论吧~  # 评论占位提示
    meta: nick,mail,link # valine comment header info
    requiredFields: ['nick','mail']
    enableQQ: true # Unstable avatar link
    recordIP: false # Record commenter IP
    avatar: robohash # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    lang: zh-cn
    highlight: true
    visitor: true
    mathJax: false